title: GGU
#subtitle: "Great Geeks United"  # TODO: do something with this
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ggu.cz" # the base hostname & protocol for your site, e.g. http://example.com
email: your-email@example.com

plugins:
  - jekyll-feed
  - jektex

collections:
  - projects
  - members
  - services

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /:year/:month/:day/:title/

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - makefile
