title: GGU
#subtitle: "Great Geeks United"  # TODO: do something with this
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ggu.cz" # the base hostname & protocol for your site, e.g. http://example.com
email: your-email@example.com

plugins:
  - jektex
  - jekyll-feed
  - jekyll-webring

collections:
  - projects
  - members
  - services

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /:year/:month/:day/:title/

webring:
  data_file: webring
  layout_file: webring
  feeds:
    - "https://blackblog.cz/feed.xml"
    - "https://slama.dev/feed.xml"
    - "https://dvdkon.ggu.cz/atom.xml"
  max_summary_length: 256
  num_items: 10
  no_item_at_date_behaviour: use_oldest
  date_format: "%-d %B, %Y"

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - makefile
  - _data/webring.yml
