title: GGU
#subtitle: "Great Geeks United"  # TODO: do something with this
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ggu.cz" # the base hostname & protocol for your site, e.g. http://example.com
email: your-email@example.com
author: "GGU Colective"
description: "We're a group of friends with similar interests from a small flat in the middle of Prague."
theme_color: "#222831"
keywords: "Free software, Open source, FOSS, OSS, Libre software, Matfyz, Svobodný software"

plugins:
  - jektex
  - jekyll-feed
  - jekyll-webring
  - jekyll-tidy

collections:
  - projects
  - members
  - services

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /:year/:month/:day/:title/

webring:
  data_file: webring
  layout_file: webring
  feeds:
    - "https://blackblog.cz/feed.xml"
    - "https://slama.dev/feed.xml"
    - "https://dvdkon.ggu.cz/atom.xml"
    - "https://grego.site/atom.xml"
  max_summary_length: 256
  num_items: 10
  no_item_at_date_behaviour: use_oldest
  date_format: "%-d %B, %Y"

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - makefile
  - _data/webring.yml


jekyll_tidy:
  exclude:
    - "**/*.scss"
    - "**/*.xml"
    - "*.xml"
    - "**/*.sass"
    - "**/*.lock"

